version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: k8s.io/metrics
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.20.5
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.20.5
  - dependency-name: k8s.io/api
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.20.5
  - dependency-name: sigs.k8s.io/controller-runtime
    versions:
    - 0.8.1
    - 0.8.2
  - dependency-name: github.com/Shopify/sarama
    versions:
    - 1.27.2
