apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subjectaccessreviews-creator
rules:
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create