apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kubernetes-kafka-connect-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - configmaps
  - events
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - watch
- apiGroups:
  - '*'
  resources:
  - ingresses
  - ingresses/status
  - routes/custom-host
  - routes/status
  - routes
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - watch
- apiGroups:
  - apps
  resourceNames:
  - kubernetes-kafka-connect-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - kafkaconnect.operator.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - get
  - create
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs: ["*"]
