kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-kafka-connect-operator
rules:
  - verbs:
      - list
      - watch
      - update
    apiGroups:
      - kafkaconnect.operator.io
    resources:
      - kafkaconnects
      - kafkaconnects/status
      - kafkaconnectautoscalers
      - kafkaconnectautoscalers/status
  - verbs:
      - get
      - create
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - list
      - watch
      - get
      - create
    apiGroups:
      - ''
    resources:
      - pods
      - services
  - verbs:
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - events
      - services
  - verbs:
      - list
      - create
      - update
      - watch
    apiGroups:
      - 'extensions'
    resources:
      - ingresses
  - verbs:
      - create
    apiGroups:
      - route.openshift.io
    resources:
      - routes/custom-host
  - verbs:
      - list
      - watch
      - create
      - update
      - get
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - get
      - update
    apiGroups:
      - apps
    resources:
      - deployments/scale
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - pods
  
  
  # - verbs:
  #     - update
  #   apiGroups:
  #     - apps
  #   resourceNames:
  #     - kubernetes-kafka-connect-operator
  #   resources:
  #     - deployments/finalizers

